version: 2

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: amazon/dynamodb-local:latest
        command:
          - -jar
          - DynamoDBLocal.jar
          - -inMemory
          - -sharedDb
          - -port
          - 8000
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew test

workflows:
  version: 2

  merge-before:
    jobs:
      - test:
          name: gradlew_test
          filters:
            branches:
              only:
                - master

