name: Master CI

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: scalafmt
      run: ./gradlew spotlessCheck
    - name: Set up DynamoDBLocal
      run:  docker run -d -p 8000:8000 amazon/dynamodb-local:latest -jar ./DynamoDBLocal.jar -inMemory -sharedDb -port 8000
    - name: Test with Gradle
      run: ./gradlew test
      env:
        RUN_AWS_CREDENTIALS_TEST: false
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports/tests/test
