name: Test CI

on:
  - push

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
        command:
          - -jar
          - DynamoDBLocal.jar
          - -inMemory
          - -sharedDb
          - -port
          - 8000

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Gradle
      run: ./gradlew test
      env:
        RUN_AWS_CREDENTIALS_TEST: false

